### ISSUE TITLE
Server crashes when sending binary data to ws-text endpoint

### ISSUE THREAD

**Issue by reneroth** [deepstreamIO/deepstream.io#1017]
I think we already had the same issue years ago in #538 and [fixed it](https://github.com/deepstreamIO/deepstream.io/commit/f8bec437774dce3c266c4c9999a5d9c6df8c85a4) easily 🙂 

What I did:
- ran stock `deepstreamio/deepstream.io:4.2.5-alpine` docker container
- used most recent client(`client/latest/ds.min.js`) to connect to the legacy `ws-text` endpoint ( `deepstream('localhost:6021')`)
- get server crash

```
rawMessage.split is not a function
    at Object.exports.parse (/src/connection-endpoint/text/protocol/message-parser.ts:48:34)
    at WebSocket.websocket.on (/src/connection-endpoint/text/connection-endpoint.ts:71:44)
    at WebSocket.emit (events.js:198:13)
    at Receiver.receiverOnMessage (/node_modules/ws/lib/websocket.js:800:20)
    at Receiver.emit (events.js:198:13)
    at Receiver.dataMessage (/node_modules/ws/lib/receiver.js:413:14)
    at Receiver.getData (/node_modules/ws/lib/receiver.js:352:17)
    at Receiver.startLoop (/node_modules/ws/lib/receiver.js:138:22)
    at Receiver._write (/node_modules/ws/lib/receiver.js:74:10)
    at doWrite (_stream_writable.js:415:12)
```

**Comment by yasserf** [comment]
hey!

Yeah so this is an issue since the text-protocol recieved a binary websocket. It should obviously not crash but it won't work either. You need to point it to the correct websocket url. I'll fix it so it provides a proper error when this happens. Thanks for raising!

**Comment by reneroth** [comment]
Yes, I'm aware it's not supposed to work, but it shouldn't be possible for a potential bad actor to crash our server this easily 😬 
I've seen you added this to the v5 milestone, does this mean we won't be getting a patch for v4? If the team has no time for this, I could try implementing a fix.

**Comment by yasserf** [comment]
Yeah I won't be porting back changes to V4 (mainly because upgrading from V4 to V5 should be very painless)

But if you raise a PR against the V4 branch I'll merge it in and do a release!

**Comment by yasserf** [comment]
Sorry, accidental close 🙈

**Comment by yasserf** [comment]
One last thing sorry, could you also do the opposite check and see what happens when you connect a text websocket to the binary endpoint?
