### ISSUE TITLE
Not starting without a config file

### ISSUE THREAD

**Issue by whitelizard** [deepstreamIO/deepstream.io#1036]
Node API docs first example does not work:

```
const { Deepstream } = require('@deepstream/server')
const server = new Deepstream()
```

It gives the following error output:
```
(node:28249) UnhandledPromiseRejectionWarning: Error: No config file found
    at getDefaultConfigPath (/home/blomqesb/dev/web/ds-node-service/node_modules/@deepstream/server/src/config/js-yaml-loader.ts:194:9)
    at setGlobalConfigDirectory (/home/blomqesb/dev/web/ds-node-service/node_modules/@deepstream/server/src/config/js-yaml-loader.ts:129:7)
    at Object.exports.loadConfigWithoutInitialization (/home/blomqesb/dev/web/ds-node-service/node_modules/@deepstream/server/src/config/js-yaml-loader.ts:61:22)
    at Object.exports.loadConfig (/home/blomqesb/dev/web/ds-node-service/node_modules/@deepstream/server/src/config/js-yaml-loader.ts:87:24)
    at Deepstream.loadConfig (/home/blomqesb/dev/web/ds-node-service/node_modules/@deepstream/server/src/deepstream.io.ts:455:35)
    at new Deepstream (/home/blomqesb/dev/web/ds-node-service/node_modules/@deepstream/server/src/deepstream.io.ts:91:10)
    at Object.<anonymous> (/home/blomqesb/dev/web/ds-node-service/test/bug1.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
(node:28249) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:28249) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by yasserf** [comment]
Thats actually a bug in documentation, if you don't want to use a config file you need to pass in null
