### ISSUE TITLE
Swift client status

### ISSUE THREAD

**Issue by redlock** [deepstreamIO/deepstream.io#1054]
Hello, we are using deepstream for our iOS app. However, we are unable to upgrade to the latest deepstream server version because the iOS client hasn't been updated since 2017. What is the status of iOS support for deepstream?
Thanks

**Comment by yasserf** [comment]
iOS support is currently non existent. If I was to work on it I would personally create a single SDK in C++ and wrap it to support other libraries but it's way more time consuming to setup. 

If a group of people are willing to sponsor the work (for the minimum specs required) I'm definitely open to working on it. Also open to giving feedback to any opensource ones as well.

**Comment by redlock** [comment]
Thanks for your response.
I am trying to use the latest version with the old js client (v3). However the server crashed with this stack trace:

```
2020-04-09T22:42:40.65303922Z AUTH_SUCCESSFUL | open
2020-04-09T22:42:40.794259265Z UNKNOWN_TOPIC | AUTH
2020-04-09T22:42:40.796097288Z { topic: 1, action: 1, originalTopic: 3 } false
2020-04-09T22:42:40.833895847Z TypeError: Cannot read property '1' of undefined
2020-04-09T22:42:40.83392511Z     at Object.exports.getMessage (/src/connection-endpoint/websocket/text/text-protocol/message-builder.ts:218:42)
2020-04-09T22:42:40.833929566Z     at TextWSSocketWrapper.getMessage (/src/connection-endpoint/websocket/text/socket-wrapper-factory.ts:12:31)
2020-04-09T22:42:40.833933123Z     at TextWSSocketWrapper.sendMessage (/src/connection-endpoint/base/socket-wrapper.ts:59:32)
2020-04-09T22:42:40.833936477Z     at MessageDistributor.distribute (/src/utils/message-distributor.ts:21:21)
2020-04-09T22:42:40.833939877Z     at MessageProcessor.onPermissionResponse (/src/utils/message-processor.ts:103:12)
2020-04-09T22:42:40.833942852Z     at ConfigPermission.canPerformAction (/src/services/permission/valve/config-permission.ts:92:7)
2020-04-09T22:42:40.833946533Z     at MessageProcessor.process (/src/utils/message-processor.ts:67:32)
2020-04-09T22:42:40.833949563Z     at TextWSSocketWrapper.unauthenticatedSocketWrapper.onMessage (/src/connection-endpoint/base/connection-endpoint.ts:287:12)
2020-04-09T22:42:40.833952576Z     at WebSocket.websocket.on (/src/services/http/node/node-http.ts:144:25)
2020-04-09T22:42:40.833955589Z     at WebSocket.emit (events.js:198:13)
```

I am using server version 5.0.12 and JS client version 2.3.0

**Comment by yasserf** [comment]
What features are you using the iOS client?

**Comment by redlock** [comment]
I am mainly using records.

**Comment by yasserf** [comment]
The best bet we have now is either:
- someone writes a functioning client for iOS
- we manage to get time to setup a C or Kotlin SDK that can be used by iOS

I'll close this issue for now, hopefully open open a new swift one when I feel we have the opportunity to expland
