### ISSUE TITLE
Cannot start without storage

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#197]
```javascript
TypeError: Cannot read property 'isReady' of undefined
    at new DependencyInitialiser (/Users/ronagy/Projects/GitHub/nxtedition/nxt-server/node_modules/deepstream.io/src/utils/dependency-initialiser.js:23:22)
    at Deepstream.start (/Users/ronagy/Projects/GitHub/nxtedition/nxt-server/node_modules/deepstream.io/src/deepstream.io.js:142:17)
    at Object.<anonymous> (server.js:49:4)
    at Module._compile (module.js:541:32)
    at loader (/Users/ronagy/Projects/GitHub/nxtedition/nxt-server/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/ronagy/Projects/GitHub/nxtedition/nxt-server/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
```

Should probably check if a plugin is null before trying to initialise it....

**Comment by ronag** [comment]
Maybe this is as intended. Though I think deepstream should be possible to run without storage.

Either case. It's a breaking change.

**Comment by yasserf** [comment]
If you want to introduce no storage for deepstream you would need to include a noop storage provider ( since we don't have guards in deepstream for null storage providers ).

Has this change been introduced in the beta versions?

**Comment by ronag** [comment]
in the non beta version running without a storage connector works fine while in beta the server doesn't start.

**Comment by yasserf** [comment]
Running without a storage connector in pre-beta results in it using the default noop one. Same thing should occur currently, except the name isn't null and should be 'default'

Can you show me the configuration you use to set your storage connector?

**Comment by ronag** [comment]
```javascript
new DeepstreamServer({
  showLogo: false,
  webServerEnabled: true,
  tcpServerEnabled: true,
  tcpPort: config.tcpPort || 6021,
  tcpHost: config.tcpHost || '0.0.0.0',
  dependencyInitialisationTimeout: 1000,
  urlPath: '/deepstream',
  logLevel: config.logLevel || 0,
  httpServer: httpServer,
  messageConnector: new RedisMessageConnector(config.redis),
  logger: createLogger({ logger }),
  cache: new RedisCacheConnector(config.redis),
  permissionHandler: createPermissionHandler(config.permission),
  authenticationHandler: createAuthenticationHandler(config.authentication, { authenticationMiddleware })
```

**Comment by yasserf** [comment]
Ah, I see the issue, currently in beta the args are not being merged into the default.

As a workaround you can put these options inside of ( conf/config.js ), and this should be fixed by next beta release

**Comment by yasserf** [comment]
Closing in favor of #202
