### ISSUE TITLE
Unhanded Exception in RethinkDB Connector

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#216]
I don't think this is supposed to happen... shouldn't the connector do an `emit('error', ...)`?

```
/foo/node_modules/deepstream.io-storage-rethinkdb/node_modules/rethinkdb/ast.js:1522
        throw new err.RqlDriverError("Object field '" + key + "' may not be undefined");
        ^
RqlDriverError: Object field 'title' may not be undefined
    at new RqlDriverError (/foo/node_modules/deepstream.io-storage-rethinkdb/node_modules/rethinkdb/errors.js:14:13)
    at new MakeObject (/foo/node_modules/deepstream.io-storage-rethinkdb/node_modules/rethinkdb/ast.js:1522:15)
    at Function.<anonymous> (/foo/node_modules/deepstream.io-storage-rethinkdb/node_modules/rethinkdb/ast.js:3901:12)
    at Function.expr (/foo/node_modules/deepstream.io-storage-rethinkdb/node_modules/rethinkdb/util.js:39:16)
    at new MakeObject (/foo/node_modules/deepstream.io-storage-rethinkdb/node_modules/rethinkdb/ast.js:1524:37)
    at Function.<anonymous> (/foo/node_modules/deepstream.io-storage-rethinkdb/node_modules/rethinkdb/ast.js:3901:12)
    at Function.expr (/foo/node_modules/deepstream.io-storage-rethinkdb/node_modules/rethinkdb/util.js:39:16)
    at Table.<anonymous> (/foo/node_modules/deepstream.io-storage-rethinkdb/node_modules/rethinkdb/ast.js:1053:45)
    at Table.insert (/foo/node_modules/deepstream.io-storage-rethinkdb/node_modules/rethinkdb/util.js:60:16)
    at Connector._insert (/foo/node_modules/deepstream.io-storage-rethinkdb/src/connector.js:177:4)
    at Connector.set (/foo/node_modules/deepstream.io-storage-rethinkdb/src/connector.js:73:3)
    at RecordTransition._next (/foo/node_modules/deepstream.io/src/record/record-transition.js:246:25)
    at RecordTransition._onRecord (/foo/node_modules/deepstream.io/src/record/record-transition.js:198:8)
    at RecordRequest._onCacheResponse (/foo/node_modules/deepstream.io/src/record/record-request.js:55:8)
    at Command.client.get.e [as callback] (/foo/node_modules/deepstream.io-cache-redis/src/cache-connector.js:80:5)
    at normal_reply (/foo/node_modules/deepstream.io-cache-redis/node_modules/redis/index.js:714:21)
```

**Comment by yasserf** [comment]
Interesting. Generally Rethinkdb doesn't support nan or undefined ( rightfully ). This should however be caught and logged as a storage error. Will prioritise and add to roadmap. If your happy to do a pr we should have a cla in place very soon and given amount is 1.0 work world be much appretiated!

**Comment by ronag** [comment]
@yasserf: Should that invariant maybe be applied all the way to Deepstream? Otherwise one can get weird behaviours when switching between different storage connectors...

**Comment by yasserf** [comment]
Depends if the storage provider supports it. It's stored in the cache either ways. Also, json.stringify should remove keys with undefined, so it's interesting how it still gets through.

**Comment by ronag** [comment]
Got it again, probably the same:

```javascript
foo/node_modules/rethinkdb/ast.js:1522
        throw new err.RqlDriverError("Object field '" + key + "' may not be undefined");
        ^
RqlDriverError: Object field 'error' may not be undefined
    at new RqlDriverError (foo/node_modules/rethinkdb/errors.js:14:13)
    at new MakeObject (foo/node_modules/rethinkdb/ast.js:1522:15)
    at Function.<anonymous> (foo/node_modules/rethinkdb/ast.js:3901:12)
    at Function.expr (foo/node_modules/rethinkdb/util.js:39:16)
    at new MakeObject (foo/node_modules/rethinkdb/ast.js:1524:37)
    at Function.<anonymous> (foo/node_modules/rethinkdb/ast.js:3901:12)
    at Function.expr (foo/node_modules/rethinkdb/util.js:39:16)
    at Table.<anonymous> (foo/node_modules/rethinkdb/ast.js:1053:45)
    at Table.insert (foo/node_modules/rethinkdb/util.js:60:16)
    at Connector._insert (foo/node_modules/deepstream.io-storage-rethinkdb/src/connector.js:177:4)
    at Connector.set (foo/node_modules/deepstream.io-storage-rethinkdb/src/connector.js:73:3)
    at RecordTransition._next (foo/node_modules/deepstream.io/src/record/record-transition.js:246:25)
    at RecordTransition._onRecord (foo/node_modules/deepstream.io/src/record/record-transition.js:198:8)
    at RecordRequest._onCacheResponse (foo/node_modules/deepstream.io/src/record/record-request.js:55:8)
    at Command.callback (foo/node_modules/deepstream.io-cache-redis/src/cache-connector.js:83:3)
    at RedisClient.return_reply (foo/node_modules/redis/index.js:664:25)
```

**Comment by ronag** [comment]
@yasserf: Any guidance on this? It seems to occur quite often for us...

**Comment by ronag** [comment]
Avoided by https://github.com/deepstreamIO/deepstream.io-storage-rethinkdb/pull/9
