### ISSUE TITLE
Neither name nor path property found for logger

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#231]
#This seem to be a recent breaking change? I can no longer pass in my custom logger?

```
Error: Neither name nor path property found for logger
    at resolvePluginClass (/Users/ronagy/Projects/GitHub/nxtedition/nxt-server/node_modules/deepstream.io/src/config/config-initialiser.js:178:9)
    at handleLogger (/Users/ronagy/Projects/GitHub/nxtedition/nxt-server/node_modules/deepstream.io/src/config/config-initialiser.js:90:12)
    at Object.exports.initialise (/Users/ronagy/Projects/GitHub/nxtedition/nxt-server/node_modules/deepstream.io/src/config/config-initialiser.js:26:2)
    at Deepstream._loadConfig (/Users/ronagy/Projects/GitHub/nxtedition/nxt-server/node_modules/deepstream.io/src/deepstream.io.js:230:30)
    at new Deepstream (/Users/ronagy/Projects/GitHub/nxtedition/nxt-server/node_modules/deepstream.io/src/deepstream.io.js:39:7)
    at Object.<anonymous> (server.js:16:12)
    at Module._compile (module.js:541:32)
    at loader (/Users/ronagy/Projects/GitHub/nxtedition/nxt-server/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/ronagy/Projects/GitHub/nxtedition/nxt-server/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/ronagy/Projects/GitHub/nxtedition/nxt-server/src/index.js:3:1)
    at Module._compile (module.js:541:32)
```

```
const ds = new DeepstreamServer({
  // Plugins
  messageConnector: new RedisMessageConnector(config.message),
  logger: new Logger(),
  storage,
  cache
})
```

All of the sudden the logger works different than messageConnector, storage and cache?

**Comment by ronag** [comment]
Actually it's no longer possible to provide custom permission and authentication strategies?

**Comment by ronag** [comment]
Closing in favour of https://github.com/deepstreamIO/deepstream.io/issues/233
