### ISSUE TITLE
"single-notifier" error

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#244]
Any idea what can cause this during a rpc call?

```javascript
6/30/2016 11:23:35 AM/usr/src/app/node_modules/deepstream.io-client-js/src/utils/single-notifier.js:75
6/30/2016 11:23:35 AM	for( i=0; i < entries.length; i++ ) {
6/30/2016 11:23:35 AM	                     ^
6/30/2016 11:23:35 AM
6/30/2016 11:23:35 AMTypeError: Cannot read property 'length' of undefined
6/30/2016 11:23:35 AM    at SingleNotifier.recieve (/usr/src/app/node_modules/deepstream.io-client-js/src/utils/single-notifier.js:75:23)
6/30/2016 11:23:35 AM    at RecordHandler._$handle (/usr/src/app/node_modules/deepstream.io-client-js/src/record/record-handler.js:210:27)
6/30/2016 11:23:35 AM    at Client._$onMessage (/usr/src/app/node_modules/deepstream.io-client-js/src/client.js:130:42)
6/30/2016 11:23:35 AM    at Connection._onMessage (/usr/src/app/node_modules/deepstream.io-client-js/src/message/connection.js:322:17)
6/30/2016 11:23:35 AM    at emitOne (events.js:96:13)
6/30/2016 11:23:35 AM    at emit (events.js:188:7)
6/30/2016 11:23:35 AM    at TcpConnection._onData (/usr/src/app/node_modules/deepstream.io-client-js/src/tcp/tcp-connection.js:180:7)
6/30/2016 11:23:35 AM    at emitOne (events.js:96:13)
6/30/2016 11:23:35 AM    at Socket.emit (events.js:188:7)
6/30/2016 11:23:35 AM    at readableAddChunk (_stream_readable.js:172:18)
6/30/2016 11:23:35 AM    at Socket.Readable.push (_stream_readable.js:130:10)
6/30/2016 11:23:35 AM    at TCP.onread (net.js:542:20)
```

**Comment by ronag** [comment]
Wrong repo.
