### ISSUE TITLE
Detach mode doesn't work consistently ( directory specific )

### ISSUE THREAD

**Issue by yasserf** [deepstreamIO/deepstream.io#246]
```
ubuntu@ip-172-31-31-227:/usr/bin$ ./deepstream start -d
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn /deepstream.io/bin/deepstream ENOENT
    at exports._errnoException (util.js:873:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:447:9)

```

**Comment by timaschew** [comment]
Is it fixed?

**Comment by timaschew** [comment]
This is only related to the binary packaged version, right?

**Comment by timaschew** [comment]
We can just remove the `--detach` option, the status and stop will still work
