### ISSUE TITLE
RC4 Crashes on response for HTTP Webhook!!!

### ISSUE THREAD

**Issue by WolframHempel** [deepstreamIO/deepstream.io#266]
![image](https://cloud.githubusercontent.com/assets/1503717/16609983/4895ac56-4358-11e6-8c62-ef4f0b39c797.png)

**Comment by timaschew** [comment]
Same on my machine.
The last successfull log is done here: https://github.com/deepstreamIO/deepstream.io/blob/91054a1571d95db7257534e57c3c49d09b676780/src/message/connection-endpoint.js#L267

I tried to back track where the last successfull log comes from to determine where the TypeError come from, but this stack trace doesn't help me.

```
    at ConnectionEndpoint._authenticateConnection (/Users/awilhelm/dev/deepstreamio/deepstream.io/src/message/connection-endpoint.js:266:89)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Socket.onPacket (/Users/awilhelm/dev/deepstreamio/deepstream.io/node_modules/engine.io/lib/socket.js:102:14)
    at emitOne (events.js:77:13)
    at WebSocket.emit (events.js:169:7)
    at WebSocket.Transport.onPacket (/Users/awilhelm/dev/deepstreamio/deepstream.io/node_modules/engine.io/lib/transport.js:104:8)
    at WebSocket.Transport.onData (/Users/awilhelm/dev/deepstreamio/deepstream.io/node_modules/engine.io/lib/transport.js:115:8)
    at WebSocket.onData (/Users/awilhelm/dev/deepstreamio/deepstream.io/node_modules/engine.io/lib/transports/websocket.js:76:30)
    at /Users/awilhelm/dev/deepstreamio/deepstream.io/node_modules/uws/uws.js:379:20
```

**Comment by WolframHempel** [comment]
Cheers, found the issue: `handleAuthStrategy` in config-initialiser only passes the options on. Will send PR in a moment, but there is also an issue with socket's being disconnected whilst HTTP request in flight
