### ISSUE TITLE
RethinkDB Unhandled Exception

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#274]
Another one of these:

```
foo/node_modules/bluebird/js/main/async.js:43
        fn = function () { throw arg; };
                           ^
ReqlRuntimeError: Connection is closed in:
r.table("asset").changes({"includeInitial": true})
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    at ReqlRuntimeError.ReqlError [as constructor] (foo/node_modules/rethinkdb/errors.js:23:13)
    at new ReqlRuntimeError (foo/node_modules/rethinkdb/errors.js:90:51)
    at mkErr (foo/node_modules/rethinkdb/util.js:177:10)
    at Feed.IterableResult._promptNext (foo/node_modules/rethinkdb/cursor.js:169:16)
    at Feed.IterableResult._addResponse (foo/node_modules/rethinkdb/cursor.js:84:12)
    at TcpConnection.<anonymous> (foo/node_modules/rethinkdb/net.js:360:22)
    at TcpConnection.cancel (foo/node_modules/rethinkdb/util.js:26:16)
    at TcpConnection.cancel (foo/node_modules/rethinkdb/net.js:783:43)
    at wrappedCb (foo/node_modules/rethinkdb/net.js:270:17)
    at foo/node_modules/rethinkdb/net.js:280:18
    at tryCatcher (foo/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (foo/node_modules/bluebird/js/main/promise.js:480:31)
    at new Promise (foo/node_modules/bluebird/js/main/promise.js:70:37)
    at TcpConnection.<anonymous> (foo/node_modules/rethinkdb/net.js:264:33)
    at TcpConnection.close (foo/node_modules/rethinkdb/util.js:43:16)
    at foo/node_modules/rethinkdb/net.js:776:46
```

**Comment by ronag** [comment]
Not a deepstream issue. Sorry.
