### ISSUE TITLE
Cannot read property of undefined

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#286]
This could probably be handled more gracefully?

```javascript
/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
                           ^

TypeError: Cannot read property 'uploads' of undefined
    at JsonPath.setValue (/node_modules/deepstream.io/src/record/json-path.js:30:11)
    at RecordTransition._next (/node_modules/deepstream.io/src/record/record-transition.js:234:46)
    at RecordTransition._onRecord (/node_modules/deepstream.io/src/record/record-transition.js:198:8)
    at RecordRequest._onCacheResponse (/node_modules/deepstream.io/src/record/record-request.js:55:8)
    at client.get.e (/node_modules/deepstream.io-cache-redis/src/cache-connector.js:80:5)
    at tryCatcher (/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (/node_modules/bluebird/js/release/nodeify.js:23:30)
    at Promise._settlePromise (/node_modules/bluebird/js/release/promise.js:558:21)
    at Promise._settlePromise0 (/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/node_modules/bluebird/js/release/promise.js:685:18)
    at Async._drainQueue (/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:566:20)
    at tryOnImmediate (timers.js:546:5)
    at processImmediate [as _immediateCallback] (timers.js:525:5)
```

**Comment by timaschew** [comment]
Please provide more details.
It's not clear what you've executed and how you wrapped the call with a promise.
Also please provide the version of deepstream, you can use the CLI `deepstream info` to print all the informaiton

**Comment by ronag** [comment]
@timaschew: Sorry. I have so many errors right now and I don't know what's causing them. I will provide more details as soon as I have them myself.

**Comment by ronag** [comment]
@timaschew: Seems to be related to upgrading the rethinkdb connector from 0.1.0 to 1.0.0

**Comment by yasserf** [comment]
This issue is due to changes in storage adaptor to save data from:

`{ v: 1, _d: { name: bob } }` to `{ name:bob, __ds: { v: 1} }`

As mentioned in 1.0.0 release notes:

Compatibility issues / Breaking Changes

deepstream metadata is now stored within each record under __ds to improve querying. Updating to this version will require data to be migrated to new structure.
Now
```
{
   "name": "John'",
   "age": "24",
   "__ds": {
     "_v": "10"
   }
}
```
Before:
```
{
     "_v": "10",
   "_d": {
      "name": "John",
      "age": "24"
   }
}
```

**Comment by ronag** [comment]
@yasserf: Ah, yes. Now I remember that commit. Sorry. I think this is what caused some of my sudden issues.

**Comment by ronag** [comment]
https://github.com/deepstreamIO/deepstream.io/issues/286#issuecomment-232302079
