### ISSUE TITLE
Error with clustered redis for cache and message + mongo for storage

### ISSUE THREAD

**Issue by cpoyraz** [deepstreamIO/deepstream.io#465]
I configured deepstream with config the below
- Message: redis server 3 cluster with 3 replicas
- Cache: redis server 3 clusters with 3 replicas
- Storage: single mongodb
And here is plugins part in config file.
```
plugins:
  message:
    name: redis
    options:
      nodes:
        - host: 192.168.1.33
          port: 7000
        - host: 192.168.1.33
          port: 7001
        - host: 192.168.1.33
          port: 7002
        - host: 192.168.1.33
          port: 7003
        - host: 192.168.1.33
          port: 7004
        - host: 192.168.1.33
          port: 7005
      maxRedirections: 16
#      redisOptions:
#        password: 'fallback-password'
  cache:
    name: redis
    options:
      nodes:
        - host: 192.168.1.33
          port: 6500
        - host: 192.168.1.33
          port: 6501
        - host: 192.168.1.33
          port: 6502
        - host: 192.168.1.33
          port: 6503
        - host: 192.168.1.33
          port: 6504
        - host: 192.168.1.33
          port: 6505
      maxRedirections: 16
#      redisOptions:
#        password: 'fallback-password'
  storage:
   name: mongodb
   options:
     connectionString: 'mongodb://127.0.0.1:27017'
     database: 'DeepStream'
     defaultTable: 'someTable'
     splitChar: '/'

```

when I run deeptsream, it gives error like

```
INFO | logger ready
INFO | deepstream version: 2.0.1
INFO | configuration file loaded from conf\config.yml
INFO | library directory set to: D:\MQ\OTHER\DEEPSTREAM-CLUSTER\lib
INFO | authenticationHandler ready: none
INFO | permissionHandler ready: valve permissions loaded from D:\MQ\OTHER\DEEPSTREAM-CLUSTER\conf\permissions.yml
INFO | storage ready
INFO | cache ready
INFO | messageConnector ready
INFO | Listening for health checks on path /health-check
CLUSTER_JOIN | iw7falsn-14rothaovxc08
INFO | Listening for websocket connections on 0.0.0.0:6020/deepstream
INFO | Deepstream started
Error: Uncaught, unspecified "error" event. (REDIS error:Error: connect ETIMEDOUT)
{ Error: Uncaught, unspecified "error" event. (REDIS error:Error: connect ETIMEDOUT)
    at Connection.emit (events.js:163:17)
    at Connection._onError (D:\MQ\OTHER\DEEPSTREAM-CLUSTER\lib\deepstream.io-msg-redis\src\connection.js:97:8)
    at emitOne (events.js:96:13)
    at Redis.emit (events.js:188:7)
    at Redis.silentEmit (D:\MQ\OTHER\DEEPSTREAM-CLUSTER\lib\deepstream.io-msg-redis\node_modules\ioredis\lib\redis.js:464:22)
    at D:\MQ\OTHER\DEEPSTREAM-CLUSTER\lib\deepstream.io-msg-redis\node_modules\ioredis\lib\redis\event_handler.js:114:10
    at Socket.<anonymous> (D:\MQ\OTHER\DEEPSTREAM-CLUSTER\lib\deepstream.io-msg-redis\node_modules\ioredis\lib\redis.js:291:43)
    at Socket.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:339:8)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5) context: 'REDIS error:Error: connect ETIMEDOUT' }
CLUSTER_LEAVE | iw7falsn-14rothaovxc08

```
Why does it occur? Do you see the reason?

**Comment by AlexBHarley** [comment]
@cpoyraz I've set up a message and cache cluster as well as mongo, just as you have and haven't been able to recreate this. Is there any other info you can provide about this?

**Comment by cpoyraz** [comment]
It occurs in Windows 10 (Build 1607) and After that, I tried in Linux(ubuntu 16.04) and same config but different error which is "(REDIS error:Error: connect ECONNREFUSED 127.0.0.1:6379". Deepstream tries to connect local redis instance but config is like above.

**Comment by cpoyraz** [comment]
And When I try with single redis host for msg and cache. It runs properly.

**Comment by cpoyraz** [comment]
I just tried to connect via ioredis to clustered redis'es and it connects and changes a key's value  successfully .

**Comment by yasserf** [comment]
Meta comment:

This issue seems to be two folds:

1- error not being handled graceful
2- clustering not working correctly

**Comment by AlexBHarley** [comment]
Have just managed to recreate this on ubuntu 16.04, am looking into it now

**Comment by cpoyraz** [comment]
@yasserf It does not seem any problem in clustering.. setting a value and getting it from another node...redirection to correct node.. it does them properly.

I tried to do several times in Linux, it gives same error below. It is so weird!

```
INFO | logger ready
INFO | deepstream version: 2.0.1
INFO | configuration file loaded from /etc/deepstream/config.yml
INFO | library directory set to: /var/lib/deepstream
INFO | authenticationHandler ready: none
Error: Uncaught, unspecified "error" event. (REDIS error:Error: connect ECONNREFUSED 127.0.0.1:6379)

```

**Comment by yasserf** [comment]
@cpoyraz Sorry I meant redis cluster connections!

**Comment by cpoyraz** [comment]
It works. Thank you so much.
