### ISSUE TITLE
deepstream crashes on log-in with empty users file

### ISSUE THREAD

**Issue by ChristophConrads-deepstreamHub** [deepstreamIO/deepstream.io#512]
The server crashes as soon as the first client attempts to log in.

Error message:
```
TypeError: Cannot read property 'JohnDoe' of undefined
TypeError: Cannot read property 'JohnDoe' of undefined
    at FileBasedAuthenticationHandler.isValidUser (/Users/christoph/node_modules/deepstream.io/src/authentication/file-based-authentication-handler.js:66:32)
    at ConnectionEndpoint._authenticateConnection (/Users/christoph/node_modules/deepstream.io/src/message/connection-endpoint.js:290:41)
    at onServerMessage (/Users/christoph/node_modules/uws/uws.js:14:15)
handleError Can't connect! Deepstream server unreachable on ws://localhost:6020/deepstream connectionError C
```

Expected behavior:
no crash, maybe an error message when reading the users file

**Comment by ChristophConrads-deepstreamHub** [comment]
[zipped demo code](https://github.com/deepstreamIO/deepstream.io/files/670803/empty-users-file.zip)
