### ISSUE TITLE
error in setting StorageExlusion

### ISSUE THREAD

**Issue by cpoyraz** [deepstreamIO/deepstream.io#513]
I updated config file for storageExclusion with the value "^d/.*" and deepstream server gives the error below
this._options.storageExclusion.test is not a function

**Comment by ronag** [comment]
You should give it a regex not a string, i.e. `/^d/.*`. Though one could argue it should handle strings as well...

**Comment by cpoyraz** [comment]
I changed it with yours, unfortunately it gives the same error like below

TypeError: this._options.storageExclusion.test is not a function
TypeError: this._options.storageExclusion.test is not a function
    at RecordTransition._next (nexe.js:28157:74)
    at RecordTransition._onRecord (nexe.js:28105:10)
    at RecordRequest._onCacheResponse (nexe.js:27745:10)
    at client.get.e (C:\..\Cluster\deepstream-iot-6020\lib\deepstream.io-cache-redis\src\cache-connector.js:95:5)
    at tryCatcher (C:\..\Cluster\deepstream-iot-6020\lib\deepstream.io-cache-redis\node_modules\ioredis\node_modules\bluebird\js\release\util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (C:\..\Cluster\deepstream-iot-6020\lib\deepstream.io-cache-redis\node_modules\ioredis\node_modules\bluebird\js\release\nodeify.js:23:30)
    at Promise._settlePromise (C:\..\Cluster\deepstream-iot-6020\lib\deepstream.io-cache-redis\node_modules\ioredis\node_modules\bluebird\js\release\promise.js:564:21)
    at Promise._settlePromise0 (C:\..\Cluster\deepstream-iot-6020\lib\deepstream.io-cache-redis\node_modules\ioredis\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\..\Cluster\deepstream-iot-6020\lib\deepstream.io-cache-redis\node_modules\ioredis\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (C:\..\Cluster\deepstream-iot-6020\lib\deepstream.io-cache-redis\node_modules\ioredis\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (C:\..\Cluster\deepstream-iot-6020\lib\deepstream.io-cache-redis\node_modules\ioredis\node_modules\bluebird\js\release\async.js:148:10)
    at Immediate.Async.drainQueues (C:\..\Cluster\deepstream-iot-6020\lib\deepstream.io-cache-redis\node_modules\ioredis\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)

**Comment by WolframHempel** [comment]
I think it's still missing a trailing slash, try `/^d\/.*/`

**Comment by cpoyraz** [comment]
I tried it, it works but it does not exclude the records like "d/283782".

**Comment by ronag** [comment]
> Is there any way to stop storing completely

Use a exclusion rule like `/.*/`

**Comment by yasserf** [comment]
>  Is there any way to stop storing completely? Is it suitable to comment out the part storage in the config?

Yes, just commenting out the storage plugin results in your using a local storage. Doing what ronag recommended

> Use an exclusion rule like /.*/

Means it won't be stored in memory either, which may be preferable, as long as your cache is perm

**Comment by yasserf** [comment]
Removed from 2.1.3 milestone since its not as critical and I couldn't find a global options hook to validate it in.

**Comment by yasserf** [comment]
This has been removed in favour of `storageExclusionPrefixes` since v3
