### ISSUE TITLE
Logging after logger is destroyed - Fatal Exception

### ISSUE THREAD

**Issue by Iiridayn** [deepstreamIO/deepstream.io#527]
**What happened:**
```
RECORD_UPDATE_ERROR | Received update for non-existant record test.ixi3tc23-1c0da2udeso
/app/node_modules/bluebird/js/main/async.js:43
        fn = function () { throw arg; };
                           ^

TypeError: Cannot read property 'logger' of null
    at RecordTransition._onStorageResponse (/app/node_modules/deepstream.io/src/record/record-transition.js:387:18)
    at tryCatcher (/app/node_modules/bluebird/js/main/util.js:26:23)
    at Promise.successAdapter (/app/node_modules/bluebird/js/main/nodeify.js:23:30)
    at Promise._settlePromiseAt (/app/node_modules/bluebird/js/main/promise.js:582:21)
    at Promise._settlePromises (/app/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/app/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/app/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/app/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
```

**What I was doing:**

The cause appears to have been setting a value (indirectly via knockout, so it may have been delayed), then calling delete on the record. This is the only thing I changed immediately before the crash. Removing that line prevented the crash, adding it back caused it to crash again.

**What I expected to happen:**

The error/warning is fine and good even; the crash is not desirable.

**Comment by WolframHempel** [comment]
Thanks for raising, this is a genuine logic error in record-transition. `destroy()` nulls the options, yet line 386 states

```javascript
if (this.isDestroyed) {
    this._options.logger.log
```

Will fix asap

**Comment by sdressler** [comment]
Are there any news on this issue?

I am currently on exploring the Postgres connector and fiddled around with the write-buffering. I noticed that DS crashes almost always when calling `callback(error)`  at `RecordTransition._onStorageResponse`. This only happens when the callback is stored in the `WriteOperations`, not when called direct on `set`, i.e. without the buffering.

**Comment by sdressler** [comment]
Turns out, that I forgot to clean the list of callbacks and then they are called twice although the record at the other end already received it.

**Comment by yasserf** [comment]
Removing line since we don't kill transition until all responses come through
