### ISSUE TITLE
deepstream.io crashes when receiving a binary WebSockets frame

### ISSUE THREAD

**Issue by ChristophConrads-deepstreamHub** [deepstreamIO/deepstream.io#538]
Frame flags: FIN, opcode 0x2

```
INFO | Deepstream started
INCOMING_CONNECTION | from undefined (127.0.0.1)
TypeError: message.split is not a function
TypeError: message.split is not a function
    at Function.parse (nexe.js:25076:33)
    at ConnectionEndpoint._processConnectionMessage (nexe.js:24518:31)
    at onServerMessage (nexe.js:843:15)
CLUSTER_LEAVE | iy67whyc-1la87x1p8uww
[ec2-user@ip-172-31-20-98 deepstream.io-client-cpp]$ echo $?
1
```

deepstream 2.1.2 on Amazon Linux AMI

**Comment by yasserf** [comment]
Good catch!
