### ISSUE TITLE
Java client does not reconnects to Deepstream

### ISSUE THREAD

**Issue by pasha30** [deepstreamIO/deepstream.io#591]
Hi, Like NodeJS client reconnects when deepstream restarts java client is not reconnecting  , its just showing 
Error occured null CONNECTION_ERROR failed to connect to /192.168.1.95 (port 6020) after 90000ms: isConnected failed: ECONNREFUSED (Connection refused)

can we have same feature in java too? is there anything which we can do to reconnect automatically if server restarts

**Comment by yasserf** [comment]
Hey, this is certainly odd. Alex is currently writing up an example android app and will look into it!

**Comment by AlexBHarley** [comment]
@pasha30, I'm not able to recreate this, testing locally but it shouldn't be any different. Here I'm just printing the raw messages received by the client. It seems to reconnect fine.

```
Raw:CCH
Raw:CA
Raw:AA
// here I kill the server
Exception in thread "Timer-1" io.deepstream.DeepstreamException: CONNECTION_ERROR: Connection refused
	at io.deepstream.DeepstreamClientAbstract.onError(DeepstreamClientAbstract.java:59)
	at io.deepstream.Connection$1.run(Connection.java:187)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Exception in thread "Timer-3" io.deepstream.DeepstreamException: CONNECTION_ERROR: Connection refused
	at io.deepstream.DeepstreamClientAbstract.onError(DeepstreamClientAbstract.java:59)
	at io.deepstream.Connection$1.run(Connection.java:187)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Exception in thread "Timer-5" io.deepstream.DeepstreamException: CONNECTION_ERROR: Connection refused
	at io.deepstream.DeepstreamClientAbstract.onError(DeepstreamClientAbstract.java:59)
	at io.deepstream.Connection$1.run(Connection.java:187)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
// here I start the server back up
Raw:CCH
Raw:CA
Raw:AA
```

How long is the connection down for? The client will only try reconnect 5 times by default, after that it will just close.

Is there any further info you can give us?

**Comment by pasha30** [comment]
What is the maximum time to reconnect?is it different from node js client?

**Comment by AlexBHarley** [comment]
Sorry for the late reply, the options you're looking for are these. These values are integers, so you can specify `Integer.MAX_VALUE` if you want the biggest possible value for any of them.

```
RECONNECT_INTERVAL_INCREMENT: 4000
MAX_RECONNECT_INTERVAL: 1500
MAX_RECONNECT_ATTEMPTS: 5
```
