### ISSUE TITLE
npm version of deepstream server cannot start

### ISSUE THREAD

**Issue by hatelove85911** [deepstreamIO/deepstream.io#769]
I'm following this tutorial have deepstream installed.
https://deepstream.io/install/npm/

But when I try starting the server, I got the following error:
```
   __| | ___  ___ _ __  ___| |_ _ __ ___  __ _ _ __ ____ 
  / _` |/ _ \/ _ \ '_ \/ __| __| '__/ _ \/ _` | '_ ` _  \
 | (_| |  __/  __/ |_) \__ \ |_| | |  __/ (_| | | | | | |
  \__,_|\___|\___| .__/|___/\__|_|  \___|\__,_|_| |_| |_|
                 |_|
 =====================   starting   ======================
INFO | state transition (start): Stopped -> LoggerInit
INFO | logger ready: std out/err
INFO | state transition (logger-started): LoggerInit -> PluginInit
INFO | deepstream version: 3.0.0
INFO | storage ready: no storage connector specified
INFO | cache ready: local cache
INFO | authenticationHandler ready: none
INFO | permissionHandler ready: none
INFO | state transition (plugins-started): PluginInit -> ServiceInit
INFO | state transition (services-started): ServiceInit -> ConnectionEndpointInit
CONNECTION_ERROR | Error: listen EADDRINUSE 127.0.0.1:6020
CONNECTION_ERROR | Error: listen EADDRINUSE 127.0.0.1:6020
PLUGIN_ERROR | connectionEndpoint wasn't initialised in time
/home/junshen/paipai_server/node_modules/deepstream.io/src/utils/dependency-initialiser.js:96
  throw error
  ^

Error: connectionEndpoint wasn't initialised in time
    at DependencyInitialiser._onTimeout (/home/junshen/paipai_server/node_modules/deepstream.io/src/utils/dependency-initialiser.js:94:17)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
```

I've checked the port, there's no process occupying the port 6020. I also tried changing the port, but it still doesn't work!!

**Comment by Weffe** [comment]
I've also been having the same issues as well! Nothing is occupying the port yet I have no issues. I am on Node v6.10.3 and NPM v5.3.0

**Comment by yasserf** [comment]
Thanks for raising, certainly odd! Will take a look at it today

**Comment by yasserf** [comment]
Thanks for raising, certainly odd! Will take a look at it today

**Comment by yasserf** [comment]
Hey, this issue is based on the invalid configuration inside of the npm install.

```
const DeepstreamServer = require('deepstream.io')
const C = DeepstreamServer.constants
/*
The server can take
1) a configuration file path
2) null to explicitly use defaults to be overriden by server.set()
3) left empty to load the base configuration from the config file located within the conf directory.
4) pass some options, missing options will be merged with the base configuration
*/
const server = new DeepstreamServer('./path/to/config.yml')

// start the server
server.start()
```

I would recommend pointing to a config path, but http as a top level parameter is generally no longer supported in 3.0, since it is ambiguous to which connection endpoint you are pointing towards. Sorry for the confusion
