### ISSUE TITLE
Permissionhandling error

### ISSUE THREAD

**Issue by MedSolve** [deepstreamIO/deepstream.io#778]
I get the following error: 
```javascript
TypeError: Cannot read property 'regexp' of null
    at ConfigPermissionHandler.canPerformAction (/Users/mrmusling/Programmering/backend/node_modules/deepstream.io/src/permission/config-permission-handler.js:173:21)
    at RecordHandler._permissionAction (/Users/mrmusling/Programmering/backend/node_modules/deepstream.io/src/record/record-handler.js:692:35)
    at RecordHandler.onComplete (/Users/mrmusling/Programmering/backend/node_modules/deepstream.io/src/record/record-handler.js:234:12)
    at onStorageResponse (/Users/mrmusling/Programmering/backend/node_modules/deepstream.io/src/record/record-request.js:37:16)
    at options.storage.get (/Users/mrmusling/Programmering/backend/node_modules/deepstream.io/src/record/record-request.js:84:9)
    at params.collection.findOne (/Users/mrmusling/Programmering/backend/node_modules/deepstream.io-storage-mongodb/src/connector.js:120:9)
    at handleCallback (/Users/mrmusling/Programmering/backend/node_modules/mongodb/lib/utils.js:96:12)
    at /Users/mrmusling/Programmering/backend/node_modules/mongodb/lib/collection.js:1335:5
    at handleCallback (/Users/mrmusling/Programmering/backend/node_modules/mongodb/lib/utils.js:96:12)
    at /Users/mrmusling/Programmering/backend/node_modules/mongodb/lib/cursor.js:665:5
```

My permissions settings are as followed:
```json
{
  "record": {
    "*": {
      "read": true
    }
  },
  "event": {
    "*": {
      "publish": true,
      "subscribe": true,
      "listen": true
    }
  },
  "rpc": {
    "*": {
      "provide": true,
      "request": true
    }
  },
  "presence": {
    "*": {
      "allow": true
    }
  }
}
```

When i from client side bind to record *questionaire* everything works fine but when i create a second binding to *questionaireResponse* i  get the error. 

"deepstream.io": "^2.3.6",
 "deepstream.io-storage-mongodb": "^1.0.2",

**Comment by MedSolve** [comment]
*ConfigPermissionHandler.prototype._getCompiledRulesForName* in *src/permission/config-permission-handler.js*. If no rules are defined then null will be returned, i can easily modify it to return an empty set instead, but is that the intended behavior?

**Comment by MedSolve** [comment]
dublicate of #497
