### ISSUE TITLE
INVALID_MESSAGE | Invalid auth message undefnied

### ISSUE THREAD

**Issue by jshrt** [deepstreamIO/deepstream.io#823]
#The deepstream.io server goes down with the following error message when trying to setData for a record without having logged in.

```
INFO | Listening for health checks on path /health-check
INFO | connectionEndpoint ready: HTTP connection endpoint
INFO | State transition (connection-endpoints-started): CONNECTION_ENDPOINT_INIT -> RUNNING
INFO | Deepstream started
INCOMING_CONNECTION | from undefined (127.0.0.1)
INVALID_MESSAGE | invalid auth message undefined

/home/jshrt/Workspace/projects/deepstream/io/deepstream.io/protocol/text/src/message-builder.ts:209
  return builder(message, errorAction, errorMessage)
         ^
TypeError: builder is not a function
    at Object.exports.getErrorMessage (/home/jshrt/Workspace/projects/deepstream/io/deepstream.io/protocol/text/src/message-builder.ts:209:10)
    at UwsSocketWrapper.sendError (/home/jshrt/Workspace/projects/deepstream/io/deepstream.io/src/message/uws/socket-wrapper-factory.ts:114:24)
    at UWSConnectionEndpoint._authenticateConnection (/home/jshrt/Workspace/projects/deepstream/io/deepstream.io/src/message/uws/connection-endp
```
This issue is reproduced in: https://github.com/deepstreamIO/test-scripts/blob/master/records/invalid-auth-msg.js

**Comment by yasserf** [comment]
Nice catch

**Comment by jshrt** [comment]
This issue is fixed is v4 (_find full script in:https://github.com/deepstreamIO/test-scripts/commit/9acf7fb111b90b27d05a3af0620d3adbaedf0989_)
