### ISSUE TITLE
Missing Windows binary release for deepstreamio 3.1.1

### ISSUE THREAD

**Issue by layanto** [deepstreamIO/deepstream.io#844]
There is no deepstreamio 3.1.1 binary release for Windows.

**Comment by knightlore** [comment]
Same problem...any news on this?

**Comment by yasserf** [comment]
@MuriloFrade any chance we can get the binary built again and uploaded? CI is broken

**Comment by layanto** [comment]
Will upgrading to 3.1.1 first make it easier to upgrade to 4.0 later? If so, 3.1.1 binary release for Windows would be great. Thanks.

**Comment by yasserf** [comment]
It won't make much of a difference tbh, v4 uses a binary protocol and contains the same backward breaking changes. Apologies for not uploading the 3.1.1 version, it isn't compiling on windows and v4 does (due to a node 8 compilation change)

**Comment by layanto** [comment]
Any chance of compiling Windows build for v4 RC?

**Comment by layanto** [comment]
Windows build for 3.1.3 released but I am getting this error
```
Error: No such module: uws_builtin
    at native ([eval]:697:28)
    at Object.11.events ([eval]:714:3)
    at o ([eval]:1:265)
    at [eval]:1:316
    at Object.237.../../constants/constants ([eval]:47938:13)
    at o ([eval]:1:265)
    at [eval]:1:316
    at Object.236.../../constants/constants ([eval]:47209:23)
    at o ([eval]:1:265)
    at [eval]:1:316
{ Error: Cannot find module './uws_win32_57'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at o ([eval]:1:125)
    at [eval]:1:316
    at native ([eval]:699:20)
    at Object.11.events ([eval]:714:3)
    at o ([eval]:1:265)
    at [eval]:1:316 code: 'MODULE_NOT_FOUND' }
[eval]:710
            throw new Error('Compilation of WebSockets has failed and there is no pre-compiled binary ' +

Error: Compilation of WebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'.
    at native ([eval]:710:19)
    at Object.11.events ([eval]:714:3)
    at o ([eval]:1:265)
    at [eval]:1:316
    at Object.237.../../constants/constants ([eval]:47938:13)
    at o ([eval]:1:265)
    at [eval]:1:316
    at Object.236.../../constants/constants ([eval]:47209:23)
    at o ([eval]:1:265)
    at [eval]:1:316
```
