### ISSUE TITLE
Server crashes on record trying to send existing version

### ISSUE THREAD

**Issue by jshrt** [deepstreamIO/deepstream.io#862]
Using the following script:

```
const deepstream = require('deepstream.io-client-js')
const BBPromise = require('bluebird').Promise
const server = require('./server')

const run = async () => {
  await server.start()

  const clientA = deepstream('localhost:6020', {
    reconnectIntervalIncrement: 100,
    maxReconnectInterval: 1000,
    maxReconnectAttempts: 999,
  })

  const clientB = deepstream('localhost:6020', {
    reconnectIntervalIncrement: 100,
    maxReconnectInterval: 1000,
    maxReconnectAttempts: 999,
  })

  await clientA.login({})
  await clientB.login({})

  const recordcA = clientA.record.getRecord('test')
  await recordcA.whenReady()

  const recordcB = clientB.record.getRecord('test')
  await recordcB.whenReady()

  await server.stop()

  await BBPromise.delay(1000)

  recordcA.set({ hello: 'there' })
  recordcB.set({ id: 1 })

  await BBPromise.delay(1000)

  recordcA.discard()
  recordcB.discard()

  await BBPromise.delay(1000)

  await server.start()
}

run()
```

The server crashes with the following error:
```
    throw new Error(`invalid ${TOPIC[message.topic]} ${(ACTIONS as any)[message.topic][action] || action}: ${metaError}`)
          ^
Error: invalid RECORD VERSION_EXISTS: meta object has unknown key a
    at Object.getMessage (/home/jshrt/Workspace/projects/deepstream/io/v4-test/node_modules/deepstream.io/protocol/binary/src/message-builder.ts:93:11)
    at UwsSocketWrapper.sendMessage (/home/jshrt/Workspace/projects/deepstream/io/v4-test/node_modules/deepstream.io/src/message/uws/socket-wrapper-factory.ts:113:30)

```
---
_You can find this script in: https://github.com/deepstreamIO/test-scripts/commit/4aa25d0062ae5aac5802c413215504bf2b3b202e_

**Comment by yasserf** [comment]
This is fixed as we no longer use the binary validator (also was fixed in there before)
