### ISSUE TITLE
deepstream failed to start for: no such module: uws_builtin

### ISSUE THREAD

**Issue by devfans** [deepstreamIO/deepstream.io#899]
I followed official installation guide to install deepstream.io on ubuntu 16.04 x64, and got this:
```
$ deepstream start
Error: No such module: uws_builtin
    at native ([eval]:697:28)
    at Object.11.events ([eval]:714:3)
    at o ([eval]:1:265)
    at [eval]:1:316
    at Object.237.../../constants/constants ([eval]:47938:13)
    at o ([eval]:1:265)
    at [eval]:1:316
    at Object.236.../../constants/constants ([eval]:47209:23)
    at o ([eval]:1:265)
    at [eval]:1:316
{ Error: Cannot find module './uws_linux_57'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at o ([eval]:1:125)
    at [eval]:1:316
    at native ([eval]:699:20)
    at Object.11.events ([eval]:714:3)
    at o ([eval]:1:265)
    at [eval]:1:316 code: 'MODULE_NOT_FOUND' }
[eval]:710
            throw new Error('Compilation of WebSockets has failed and there is no pre-compiled binary ' +
            ^

Error: Compilation of WebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'.
    at native ([eval]:710:19)
    at Object.11.events ([eval]:714:3)
    at o ([eval]:1:265)
    at [eval]:1:316
    at Object.237.../../constants/constants ([eval]:47938:13)
    at o ([eval]:1:265)
    at [eval]:1:316
    at Object.236.../../constants/constants ([eval]:47209:23)
    at o ([eval]:1:265)
    at [eval]:1:316
```

Any idea how to fix it? I tried ```npm i -g uws``` and seems doesn't help.

**Comment by devfans** [comment]
Tried version 3.1.1, working good.

**Comment by riartem** [comment]
3.1.3 Same error

**Comment by nasersobhan** [comment]
CentOS is the same.

Error: No such module: uws_builtin
    at native ([eval]:697:28)
    at Object.11.events ([eval]:714:3)
    at o ([eval]:1:265)
    at [eval]:1:316
    at Object.237.../../constants/constants ([eval]:47938:13)
    at o ([eval]:1:265)
    at [eval]:1:316
    at Object.236.../../constants/constants ([eval]:47209:23)
    at o ([eval]:1:265)
    at [eval]:1:316
{ Error: Cannot find module './uws_linux_57'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at o ([eval]:1:125)
    at [eval]:1:316
    at native ([eval]:699:20)
    at Object.11.events ([eval]:714:3)
    at o ([eval]:1:265)
    at [eval]:1:316 code: 'MODULE_NOT_FOUND' }
[eval]:710
            throw new Error('Compilation of WebSockets has failed and there is no pre-compiled binary ' +
            ^

Error: Compilation of WebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'.
    at native ([eval]:710:19)
    at Object.11.events ([eval]:714:3)
    at o ([eval]:1:265)
    at [eval]:1:316
    at Object.237.../../constants/constants ([eval]:47938:13)
    at o ([eval]:1:265)
    at [eval]:1:316
    at Object.236.../../constants/constants ([eval]:47209:23)
    at o ([eval]:1:265)
    at [eval]:1:316

**Comment by riartem** [comment]
Rolling back to 3.1.1 helps for me for now. But still wait for fix in future releases.
Who wants to roll back, quick steps (for Ubuntu):

1. `sudo apt-get remove deepstream.io`
2. `cd ~`
3. `wget https://github.com/deepstreamIO/deepstream.io/releases/download/v3.1.1/deepstream.io_3.1.1_amd64.deb`
4. `sudo dpkg -i deepstream.io_3.1.1_amd64.deb`

**Comment by yasserf** [comment]
hello,

does it work for you now with the 3.1.4 release? The build mechanism failed massively due to c++/nodejs/uws incompatabilities

**Comment by riartem** [comment]
@yasserf Hello! Now looks like starting fine. 
Need more time to better testing.

**Comment by yasserf** [comment]
Happy to hear!

**Comment by riartem** [comment]
@yasserf Thank you so much!

**Comment by yasserf** [comment]
Closing this issue for now. 

Need to push a docker image and figure out osx issue.
