### ISSUE TITLE
can not run in window 10

### ISSUE THREAD

**Issue by StellaLim** [deepstreamIO/deepstream.io#900]
I download the deepstream.io-windows-3.1.3 version and then  Unzip . However when I use cmd to run the deepsteam.exe there are some error  as follow 
```
Error: No such module: uws_builtin
    at native ([eval]:697:28)
    at Object.11.events ([eval]:714:3)
    at o ([eval]:1:265)
    at [eval]:1:316
    at Object.237.../../constants/constants ([eval]:47938:13)
    at o ([eval]:1:265)
    at [eval]:1:316
    at Object.236.../../constants/constants ([eval]:47209:23)
    at o ([eval]:1:265)
    at [eval]:1:316
{ Error: Cannot find module './uws_win32_57'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at o ([eval]:1:125)
    at [eval]:1:316
    at native ([eval]:699:20)
    at Object.11.events ([eval]:714:3)
    at o ([eval]:1:265)
    at [eval]:1:316 code: 'MODULE_NOT_FOUND' }
[eval]:710
            throw new Error('Compilation of WebSockets has failed and there is no pre-compiled binary ' +
            ^

Error: Compilation of WebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'.
    at native ([eval]:710:19)
    at Object.11.events ([eval]:714:3)
    at o ([eval]:1:265)
    at [eval]:1:316
    at Object.237.../../constants/constants ([eval]:47938:13)
    at o ([eval]:1:265)
    at [eval]:1:316
    at Object.236.../../constants/constants ([eval]:47209:23)
    at o ([eval]:1:265)
    at [eval]:1:316
```
My enviroment as follow:
node : V8.11.3
Python: 3.6.5
OS: window 10

**Comment by StellaLim** [comment]
change the deepsteam.io for window version to V3.1.0 can solve this problem.
