### ISSUE TITLE
vc code game Cannot read property 'rpc' of undefined

### ISSUE THREAD

**Issue by zhuzi55** [deepstreamIO/deepstream.io#921]
TypeError: Cannot read property 'rpc' of undefined
    at Object.proto.pushMessageToUserID (D:\singleServers\app\servers\game\gameserver\baozhua.js:295:15)
    at D:\singleServers\app\servers\game\gameserver\baozhua.js:270:12
    at Query.<anonymous> (D:\singleServers\app\util\mysql.js:24:22)
    at Query.<anonymous> (D:\singleServers\node_modules\mysql\lib\Connection.js:502:10)
    at Query._callback (D:\singleServers\node_modules\mysql\lib\Connection.js:468:16)
    at Query.Sequence.end (D:\singleServers\node_modules\mysql\lib\protocol\sequences\Sequence.js:83:24)
    at Query._handleFinalResultPacket (D:\singleServers\node_modules\mysql\lib\protocol\sequences\Query.js:139:8)
    at Query.EofPacket (D:\singleServers\node_modules\mysql\lib\protocol\sequences\Query.js:123:8)
    at Protocol._parsePacket (D:\singleServers\node_modules\mysql\lib\protocol\Protocol.js:278:23)
    at Parser.write (D:\singleServers\node_modules\mysql\lib\protocol\Parser.js:76:12)

I got this error and the entire DS crashed. Anyone can help?

**Comment by yasserf** [comment]
hello. Sorry for the late reply. Seems the error occurred because your client isn't actually a deepstream client (I'm assuming its a nodeJS microservice).

```
const client = deepstream()
client.login(() => {
  client.rpc.make(...)
})
``` 

If that isn't the issue and you would like to try again please reopen this. Apologies for not getting back sooner.
