### ISSUE TITLE
systemd service failed, ExecStart wrong!

### ISSUE THREAD

**Issue by christiangelone** [deepstreamIO/deepstream.io#936]
Background: Deepstream 3.2.0 installed from deb package

When you run `deepstream service add` on a systemd based linux (Ubuntu 16.04)
the deepstream.service file ExecStart attribute points to `${pwd}/bin/deepstream.js daemon`
making service to run shit, because there's nothing there.

ExecStart should point to `/usr/bin/deepstream start`
`Environment` attribute should be commented
deepstream.service file should not be marked as executabl
`sudo chmod 644 /etc/systemd/system/deepstream.service`

BTW
```
sudo deepstream daemon
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn /home/vagrant/bin/deepstream.js ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at Object.<anonymous> (/usr/bin/deepstream:322:30)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at _third_party_main.js:37:36
    at NativeModule.compile (internal/bootstrap/loaders.js:362:7)
    at Function.NativeModule.require (internal/bootstrap/loaders.js:174:18)
    at internal/bootstrap/node.js:249:22
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    [... lines matching original stack trace ...]
    at internal/bootstrap/node.js:249:22
```

**Comment by yasserf** [comment]
Thank you for raising. We are currently looking into submitting a fix but
are facing an issue trying to get it working on windows. Should hopefully
get a release out in the next couple of days that fixes it and other small
teething issues with uws. If not we’ll put a release out for non windows
binaries first.

**Comment by yasserf** [comment]
Got a release out, please let me know if this works for you
