### ISSUE TITLE
Unknown option or service "storageExclusion" error after upgrading to @deepstream/server v4

### ISSUE THREAD

**Issue by KrishnaPG** [deepstreamIO/deepstream.io#959]
After upgrading to v4, the server npm package started to give error for the below line of code (which used to work fine in v3)
````
server.set('storageExclusion', /^dont-store\/*./) 
````
The error is:
````
Error: Unknown option or service "storageExclusion"
    at Deepstream.set (\node_modules\@deepstream\server\src\deepstream.io.ts:112:13)
    at Object.<anonymous> (\src\index.js:121:8)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
````

**Comment by yasserf** [comment]
Yup this is correct, although I have now added better error logging. We replace storageExclusion with storageExclusionPrefixes as its quicker to run and we are trying to slowly move away from regexes as a config option.
