### ISSUE TITLE
v4.1.0: Cannot assign to read only property 'options' of object '#<Object>'

### ISSUE THREAD

**Issue by KrishnaPG** [deepstreamIO/deepstream.io#984]
After upgrading to v4.1.0 started getting below error:
````
@deepstream\server\src\config\config-initialiser.ts:47
        connectionEndpoint.options = utils.merge(defaultPlugin.options, connectionEndpoint.options)
                                  ^
TypeError: Cannot assign to read only property 'options' of object '#<Object>'
    at Object.exports.mergeConnectionOptions (\node_modules\@deepstream\server\src\config\config-initialiser.ts:47:35)
    at Deepstream.loadConfig (\node_modules\@deepstream\server\src\deepstream.io.ts:423:25)    
    at new Deepstream (\node_modules\@deepstream\server\src\deepstream.io.ts:64:10)
````

The code in question, shown below, worked fine earlier:
````
const serverConfig = config.get("deepStreamServer");
const server = new DeepstreamServer.Deepstream(serverConfig);
````
The code (shown below) is trying to modify the supplied input config object, rather than creating its own version of whatever is required.
https://github.com/deepstreamIO/deepstream.io/blob/21826fbccaf9e1a24ed560aa4eca21cf0e67a15d/src/config/config-initialiser.ts#L47

**Comment by yasserf** [comment]
Thanks for raising, will get a fix out shortly.

**Comment by yasserf** [comment]
Actually looking further into this it looks like having a read-only config object was never supported.

For example:

```
/**
 * Transform the UUID string config to a UUID in the config object.
 */
function handleUUIDProperty (config: DeepstreamConfig): void {
  if (config.serverName === 'UUID') {
    config.serverName = utils.getUid()
  }
}
```

```
  if (LOG_LEVEL[config.logLevel]) {
    // NOTE: config.logLevel has highest priority, compare to the level defined
    // in the nested logger object
    config.logLevel = config.logLevel
    logger.setLogLevel(LOG_LEVEL[config.logLevel])
  }
```

Looks like you just got that part exposed. Normally I would just say I can serialize/unserialize but I'm not sure if theres anything it would effect, so it would be great if you can do this on your side. Thanks!
