### ISSUE TITLE
Unknown option or service "sslCert"

### ISSUE THREAD

**Issue by crapthings** [deepstreamIO/deepstream.io#987]
```
const deepstreamServer = new Deepstream({})
deepstreamServer.set('sslCert', fs.readFileSync('../server.cert'), 'utf8')
deepstreamServer.set('sslKey', fs.readFileSync('../server.key'), 'utf8')
deepstreamServer.start()
```

Error: Unknown option or service "sslCert"
    at Deepstream.set (/Users/monsterstep/dev/parcel-playground/ot/server/node_modules/@deepstream/server/src/deepstream.io.ts:112:13)
    at Object.<anonymous> (/Users/monsterstep/dev/parcel-playground/ot/server/index.js:35:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

**Comment by crapthings** [comment]
the Docs still have misleading

deepstreamServer.set('sslCert', fs.readFileSync('../server.cert'), 'utf8')

use a wss proxy for now

https://deepstream.io/docs/server/node-api/#methods

**Comment by sittingbool** [comment]
How can I set ssl only to the websocket, not http? ( since I am using a nginx proxy in front of http and it can't handle ssl proxying internally)
I would setup one http and one https connection and assign the https to the deepstreamServer - instance. Would that work?
Otherwise that set() -approach would be much cleaner.
