### ISSUE TITLE
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed

### ISSUE THREAD

**Issue by andreabat** [deepstreamIO/deepstream.io#993]
When trying to login with http webhook on version 4.2.
using same code for webhook as previous ( working) versions of deepstream.
Deepstream crashes as soon as the auth request is sent from deepstream to the webhook server.

Stack
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:409:19)
    at writeOrBuffer (_stream_writable.js:397:5)
    at Socket.Writable.write (_stream_writable.js:295:11)
    at Socket.Writable.end (_stream_writable.js:592:10)
    at Socket.end (net.js:536:31)
    at Function._terminateSocket (/data/dev/dev/lab/vivace2/deepstream/deepstream.io/src/message/uws/connection-endpoint.js:673:12)
    at UWSConnectionEndpoint._onUpgradeRequest (/data/dev/dev/lab/vivace2/deepstream/deepstream.io/src/message/uws/connection-endpoint.js:659:27)
    at Server.emit (events.js:182:13)
    at onParserExecuteCommon (_http_server.js:534:14)
    at onParserExecute (_http_server.js:481:3)
Emitted 'error' event at:
    at onwriteError (_stream_writable.js:433:12)
    at onwrite (_stream_writable.js:469:5)
    at doWrite (_stream_writable.js:409:11)
    at writeOrBuffer (_stream_writable.js:397:5)
    [... lines matching original stack trace ...]
    at Server.emit (events.js:182:13)

Config is attached.

[config.yml.txt](https://github.com/deepstreamIO/deepstream.io/files/3591019/config.yml.txt)

Auth Webhook Server
[server_send.js.txt](https://github.com/deepstreamIO/deepstream.io/files/3591048/server_send.js.txt)

**Comment by yasserf** [comment]
hey, thanks for raising. 

I'm a little confused, your config.yml is in the v3 format and I can't find these anywhere in the stack trace. What version are you upgrading from?

```
(/data/dev/dev/lab/vivace2/deepstream/deepstream.io/src/message/uws/connection-endpoint.js:673:12)
at UWSConnectionEndpoint._onUpgradeRequest (/data/dev/dev/lab/vivace2/deepstream/deepstream.io/src/message/uws/connection-endpoint.js:659:27)
```

**Comment by andreabat** [comment]
I am so sorry. I got mixed up with my different folders.
Sorry for wasting your time 
:-(

**Comment by yasserf** [comment]
No worries! Was pretty confused haha, happy it wasn’t an issue! 😁
